
name: Hello world workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_name_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world script name
        run: echo "Hello World"
        shell: bash
        
  job_name_goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodbye
        run: echo "Good bye"
        shell: bash

